import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class DataserviceService {
  dataTypes(){
    let dataypes = [
        {
        "name":"Rajiv",
        "marks":{
        "Maths":"18",
        "English":"21",
        "Science":"45"
        },
        "rollNumber":"KV2017-5A2"
        },
        {
        "name":"Abhishek",
        "marks":{
        "Maths":"43",
        "English":"30",
        "Science":"37"
        },
        "rollNumber":"KV2017-5A1"
        },
        {
          "name":"Ishu",
          "marks":{
          "Maths":"43",
          "English":"20",
          "Science":"19"
          },
          "rollNumber":"KV2017-5A9"
          },,
          {
            "name":"Abhi",
            "marks":{
            "Maths":"23",
            "English":"36",
            "Science":"37"
            },
            "rollNumber":"KV2017-5A8"
            },
            {
              "name":"Kylash",
              "marks":{
              "Maths":"13",
              "English":"30",
              "Science":"37"
              },
              "rollNumber":"KV2017-5A7"
              },
              {
                "name":"Bala",
                "marks":{
                "Maths":"43",
                "English":"20",
                "Science":"47"
                },
                "rollNumber":"KV2017-5C4"
                },
                {
                  "name":"Souji",
                  "marks":{
                  "Maths":"33",
                  "English":"22",
                  "Science":"27"
                  },
                  "rollNumber":"KV2017-5G1"
                  },
                  {
                    "name":"Jamuna",
                    "marks":{
                    "Maths":"43",
                    "English":"40",
                    "Science":"47"
                    },
                    "rollNumber":"KV2017-6A1"
                    },
                    {
                      "name":"Damodar",
                      "marks":{
                      "Maths":"45",
                      "English":"46",
                      "Science":"37"
                      },
                      "rollNumber":"KV2017-5A7"
                      },
                      {
                        "name":"Hima",
                        "marks":{
                        "Maths":"30",
                        "English":"32",
                        "Science":"32"
                        },
                        "rollNumber":"KV2017-7B2"
                        },
                        {
                          "name":"Teja",
                          "marks":{
                          "Maths":"43",
                          "English":"22",
                          "Science":"15"
                          },
                          "rollNumber":"KV2017-5C1"
                          },
        {
        "name":"Zoya",
        "marks":{
        "Maths":"42",
        "English":"31",
        "Science":"50"
        },
        "rollNumber":"KV2017-5A3"
        },
        {
          "name":"Telar",
          "marks":{
          "Maths":"42",
          "English":"41",
          "Science":"50"
          },
          "rollNumber":"KV2017-2A3"
          },
          {
            "name":"Lalitha",
            "marks":{
            "Maths":"42",
            "English":"21",
            "Science":"22"
            },
            "rollNumber":"KV2017-1A3"
            },
            {
              "name":"Mamatha",
              "marks":{
              "Maths":"24",
              "English":"34",
              "Science":"24"
              },
              "rollNumber":"KV2017-6A3"
              },
              {
                "name":"ZElina",
                "marks":{
                "Maths":"22",
                "English":"21",
                "Science":"50"
                },
                "rollNumber":"KV2017-5B3"
                },
          ];
        
        return dataypes
}}